export const englishdata = {
    mainheading:"MANAGE",
    heading:"Manage your booking",
    subheading: "Enter your details to see your itinerary, make changes and add extra services.",
    button1:"Retrieve Booking",
    cardheading:"Tailor your Riyadh experience",
    cardp1:"There’s so much you can do with our booking management tool and you can take control of your journey in justa few clicks. It’s easy and secure ‑ just have your booking reference and your last name ready to get started.",
    cardp2:"Manage your booking",
    para1:"You can edit and manage all your travel needs online. Book a dietary meal if you have a specific diet, upgrade your seat, and add a hotel or car rental to your booking. You can also book services like Chauffeur‑drive.",
    cardp3:"Check your itinerary",
    para2:"View, print or email your flight itinerary. Check your flight details and make changes to your booking.",
    cardp4:"Select a seat",
    para3:"Choose where you want to sit on the plane. Explore our immersive 3D seat map and get a feel for the experience before you select your seat. Choosing your seat on the flight also means your family or friends can sit together when you’re flying in a large group. Through Manage your booking you can change your seat at any time up until check‑in.",
    cardp5:"Update your email address and contact number ",
    para4:"Keep your details up to date so we can send you notifications about your flights’ status, any disruptions, or if there’s a chance to upgrade.",
    cardp6:"Check‑in online ",
    para5:"Save time at the airport and check‑in online between 48 hours and 90 minutes before your flight. You can also use mobile check‑in and download your boarding pass on your phone. When you check‑in online, you can choose your seat for free.",
    cardp7:"Buy excess baggage allowance",
    para6:"See the weight limit for checked‑in baggage and carry‑on baggage, and if you need more you can pay for extra baggage online for 20% less than at the airport. Check our baggage rules before you fly.",
    cardp8:"Log in to Riyadh Air",
    para7:"Manage every aspect of your loyalty account online. Add your membership number to your booking and earn Riyadh Miles on your flight, or use your Miles to upgrade. Check your Miles balance and see when they’ll expire, and find out how many Tier Miles you need to reach the next membership level. Not a member? Sign up online for free.",
    placeholder2:"Booking Reference",
    placeholder1:"Last Name"
}